using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;

namespace Scribbly.Stencil;

/// <summary>
/// Extension methods to map the stencil application the root application or group.
/// </summary>
public static class StencilApplicationExtensions
{
    /// <summary>
    /// Maps all the endpoints captured and generated by Scribbly Stencil
    /// </summary>
    /// <param name="builder">The application or route group to map all the endpoints to.</param>
    /// <param name="prefix">An optional route prefix to add to all endpoints.
    /// <remarks>When provided the endpoints wil be mapped as a group.</remarks>
    /// </param>
    /// <returns>The route builder with mapped endpoints.</returns>
    public static IEndpointRouteBuilder MapStencilEndpoints(this IEndpointRouteBuilder builder, string? prefix = null)
    {
        if (prefix is null)
        {
            return builder
                .MapLunchGroup();
        }
        
        return builder
            .MapGroup(prefix)
            .MapLunchGroup();
    }
}