using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Scribbly.Stencil.Endpoints.Context;

namespace Scribbly.Stencil.Groups;

public class GroupRegistrarExecution
{
    public static void Generate(SourceProductionContext context, ImmutableArray<TargetGroupCaptureContext> endpoints)
    {
        if (endpoints.IsDefaultOrEmpty)
            return;

        var sb = new StringBuilder($"""

                                    // <auto-generated/> @{DateTime.UtcNow}
                                    #nullable enable

                                    using System;
                                    using Microsoft.AspNetCore.Builder;
                                    using Microsoft.AspNetCore.Http;
                                    using Microsoft.AspNetCore.Mvc;
                                    using Microsoft.AspNetCore.Routing;

                                    """);

        context.AddSource($"Scribbly.Stencil.GroupRegistry.g.cs", sb.ToString());
    }
}