using System.Collections.Concurrent;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Scribbly.Stencil.Endpoints;
using Scribbly.Stencil.Endpoints.Factories;

namespace Scribbly.Stencil.Groups;

public class GroupRegistrarExecution
{
    public static void Generate(SourceProductionContext context, (ImmutableArray<TargetMethodCaptureContext> Endpoints, ImmutableArray<TargetGroupCaptureContext> Groups) tree)
    {
        if (tree.Groups.IsDefaultOrEmpty)
        {
            GenerateWithoutGroups(context, tree);
            return;
        }
        
        GenerateWithGroups(context, tree);
    }

    private static void GenerateWithGroups(SourceProductionContext context, (ImmutableArray<TargetMethodCaptureContext> Endpoints, ImmutableArray<TargetGroupCaptureContext> Groups) tree)
    {
        var (endpoints, groups) = tree;
        
        var endpointsWithoutGroup = endpoints.Where(e => e.MemberOf == null).ToList();
        
        var groupMap = groups.ToDictionary(
            g => $"{g.Namespace}.{g.TypeName}",
            v => new GroupItem($"{v.Namespace}.{v.TypeName}", v));
        
        var groupDictionary = CreateTree(groupMap);
        
        var sb = new StringBuilder($$"""
                                     // <auto-generated/> @{{DateTime.UtcNow}} @GroupRegistrarExecution.cs
                                     #nullable enable

                                     using System;
                                     using Microsoft.AspNetCore.Builder;
                                     using Microsoft.AspNetCore.Http;
                                     using Microsoft.AspNetCore.Mvc;
                                     using Microsoft.AspNetCore.Routing;
                                     
                                     {{GroupUsingStatements(groups, endpointsWithoutGroup)}}

                                     public static class GroupRegistrationExtensions
                                     {
                                         public static global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder MapStencilApp(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app)
                                         {                            
                                     """);
        
        sb.AppendLine();
        foreach (var targetMethodCaptureContext in endpointsWithoutGroup)
        {
            sb.Append("        app.").CreateEndpointMappingMethodInvocation(subject: targetMethodCaptureContext);
            sb.AppendLine();
        }
        
        sb.AppendLine();
        DebugTree(sb, groupDictionary, false);
        
        foreach (var root in groupDictionary)
        {
            EmitGroup(sb, root, parentBuilderName: "app");
        }
        
        sb.AppendLine("""
                              return app;
                          }
                      }
                      """);
        context.AddSource($"Registrar.Scribbly.Stencil.GroupRegistry.g.cs", sb.ToString());
    }
    
    private static void GenerateWithoutGroups(SourceProductionContext context, (ImmutableArray<TargetMethodCaptureContext> Endpoints, ImmutableArray<TargetGroupCaptureContext> Groups) tree)
    {
        var (endpoints, groups) = tree;
        var endpointsWithoutGroup = endpoints.Where(e => e.MemberOf == null);

        var sb = new StringBuilder($$"""
                                     // <auto-generated/> @{{DateTime.UtcNow}} @GroupRegistrarExecution.cs
                                     #nullable enable

                                     using System;
                                     using Microsoft.AspNetCore.Builder;
                                     using Microsoft.AspNetCore.Http;
                                     using Microsoft.AspNetCore.Mvc;
                                     using Microsoft.AspNetCore.Routing;
                                     
                                     {{GroupUsingStatements(groups, endpointsWithoutGroup)}}

                                     public static class GroupRegistrationExtensions
                                     {
                                         public static global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder MapStencilApp(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app)
                                         {                            
                                     """);
        
        sb.AppendLine();
        foreach (var targetMethodCaptureContext in endpoints.Where(e => e.MemberOf == null))
        {
            sb.Append("        app.Map").Append(targetMethodCaptureContext.TypeName).Append(targetMethodCaptureContext.MethodName).Append("();");
            sb.AppendLine();
        }
        
        sb.AppendLine("""
                              return app;
                          }
                      }
                      """);
        context.AddSource($"Registrar.Scribbly.Stencil.GroupRegistry.g.cs", sb.ToString());
    }
    
    private static List<GroupItem> CreateTree(Dictionary<string, GroupItem> map)
    {
        var childKeys = new HashSet<string>();

        foreach (var kvp in map)
        {
            var group = kvp.Value;

            if (!string.IsNullOrEmpty(group.Context?.MemberOf))
            {
                if (map.TryGetValue(group.Context?.MemberOf!, out var parent))
                {
                    parent.Children.Add(group);
                    childKeys.Add(group.GroupName!);
                }
            }
        }
        
        return map
            .Where(kvp => !childKeys.Contains(kvp.Key))
            .Select(kvp => kvp.Value)
            .ToList();
    }
    
    private static void EmitGroup(
        StringBuilder sb,
        GroupItem group,
        string parentBuilderName)
    {
        var builderName = CreateGroupName(group.Context);
        sb.AppendLine($"        var {builderName} = {parentBuilderName}.Map{group.Context?.TypeName}();");
        
        foreach (var child in group.Children)
        {
            EmitGroup(sb, child, builderName);
        }
    }
    
    private static string GroupUsingStatements(ImmutableArray<TargetGroupCaptureContext> groups, IEnumerable<TargetMethodCaptureContext> endpoints)
    {
        var builder = new StringBuilder();
        var namespaces = new List<string?>();
        
        namespaces.AddRange(groups.Select(g => g.Namespace));
        namespaces.AddRange(endpoints.Select(g => g.Namespace));
        
        foreach (var name in namespaces.Distinct())
        {
            builder.AppendLine($"using {name};");
        }
        return builder.ToString();
    }
    
    private static string CreateGroupName(TargetGroupCaptureContext? context)
    {
        return $"{context?.Namespace}_{context?.TypeName}".Replace(".", "_").ToLower();
    }
    
    private static StringBuilder DebugTree(StringBuilder sb, List<GroupItem> groups, bool enable)
    {
        if (!enable)
        {
            return sb;
        }
        
        foreach (var group in groups)
        {
            sb.AppendLine();
            sb.AppendLine($"//----> KEY: {group.GroupName} NAME: {group.GroupName} TYPE: {group.Context?.TypeName}");
            
            foreach (var valueChild in group.Children)
            {
                sb.AppendLine(
                    $"//---------------> CHILD: {valueChild.GroupName} TYPE: {valueChild.Context?.TypeName}");

                if (valueChild.IsParent)
                {
                    foreach (var childsChild in valueChild.Children)
                    {
                        sb.AppendLine($"//------------------------> CHILD Of CHILD: {childsChild.GroupName} TYPE: {childsChild.Context?.TypeName}");
                    }
                }
            }
        }
        
        return sb;
    }

}