using System.Runtime.CompilerServices;
using System.Text;

namespace Scribbly.Stencil.Factories;

public static class FileHeaderFactory
{
    public static StringBuilder CreateFileHeader(bool useStencil = true, [CallerMemberName] string? caller = null, [CallerFilePathAttribute] string? callerPath = null, [CallerLineNumber] int callerLineNumber = 0)
    {
        return new StringBuilder()
            .Append("// <auto-generated/> @")
            .Append(DateTime.UtcNow)
            .Append(" @")
            .AppendLine(caller)
            .Append("// ")
            .Append(callerPath)
            .Append(callerLineNumber)
            .AppendLine()
            .AppendLine("#nullable enable")
            .AppendCondition("using Scribbly.Stencil;", useStencil);
    }    
}