using Scribbly.Stencil.Groups;

namespace Scribbly.Stencil.Types.Attributes;

internal static class GroupMemberAttribute
{
    public const string FileName = "GroupMemberAttribute.g.cs";
    public const string TypeName = "GroupMemberAttribute";
    public const string UsageName = "GroupMember";
    public const string TypeFullName = "Scribbly.Stencil.GroupMemberAttribute`1";
    
    public static readonly string Value = 
        $$"""
        // <auto-generated/>
        #nullable enable

        namespace Scribbly.Stencil;

        /// <summary>
        /// 
        /// </summary>
        [AttributeUsage(AttributeTargets.Class | AttributeTargets.Method, AllowMultiple = false)]
        public sealed class {{TypeName}}<TGroup> : global::System.Attribute where TGroup : global:: {{GroupMarkerInterface.TypeFullName}}
        {
        }
        """;
}
