using System.Text;
using Scribbly.Stencil.Endpoints;
using Scribbly.Stencil.Groups;

namespace Scribbly.Stencil.Builder.Factories;

public static class ServiceRegistrationClassFactory
{
    public static StringBuilder CreateServiceRegistrar(this StringBuilder builder)
    {
        return builder.Append("""
                              // <auto-generated/>
                              #nullable enable

                              using Microsoft.Extensions.DependencyInjection;

                              namespace Scribbly.Stencil;

                              /// <summary>
                              /// Extensions used to register the Stencil application with your DI container.
                              /// </summary>
                              public static partial class 
                              """)
            .AppendLine(BuilderExtensionsClass.TypeName)
            .AppendLine("""
                        {
                            /// <summary>
                            /// Registers all stencil groups and endpoints in the DI container.
                            /// <remarks>When utilized all Groups and Endpoints will be resolved from the container.</remarks>
                            /// </summary>
                            public static IServiceCollection AddStencil(this IServiceCollection services, Action<StencilOptions>? configureOptions = null)
                            {
                                var options = new StencilOptions();
                                configureOptions?.Invoke(options);
                                
                                services.AddSingleton(options);
                                services.AddStencilHandlers(options);
                                services.AddStencilGroups(options);
                                
                                return services;
                            }
                            
                            static partial void AddStencilHandlers(this IServiceCollection services, StencilOptions options);
                            static partial void AddStencilGroups(this IServiceCollection services, StencilOptions options);
                        }
                        """);
    }
    
    public static StringBuilder CreateServiceScopeMapping(this StringBuilder builder)
    {
        return builder.Append("""
                              // <auto-generated/>
                              #nullable enable

                              using Microsoft.Extensions.DependencyInjection;

                              namespace Scribbly.Stencil;

                              /// <summary>
                              /// Extensions used to convert stencil options to 
                              /// </summary>
                              internal static class 
                              """)
            .AppendLine(ServiceScopeExtensionsClass.TypeName)
            .AppendLine("""
                        {
                            /// <summary>
                            /// Converts the stencil service scope to the Microsoft Service Scope.
                            /// <remarks>This allows stencil to be dependency free</remarks>
                            /// </summary>
                            public static ServiceLifetime ToLifetime(this StencilOptions.ServiceScope scope) =>
                                scope switch
                                {
                                    StencilOptions.ServiceScope.Transient => ServiceLifetime.Transient,
                                    StencilOptions.ServiceScope.Scoped => ServiceLifetime.Scoped,
                                    StencilOptions.ServiceScope.Singleton => ServiceLifetime.Singleton,
                                    _ => ServiceLifetime.Transient
                                };
                        }
                        """);
    }
}