using System;

namespace Scribbly.Stencil.Attributes.Groups;

    internal static class EndpointGroupAttribute
    {
        public const string FileName = "EndpointGroupAttribute.g.cs";
        public const string TypeName = "EndpointGroupAttribute";
        public const string UsageName = "EndpointGroup";
        public const string TypeFullName = "Scribbly.Stencil.EndpointGroup";
        public const string Value =
@$"
// <auto-generated/>
#nullable enable
namespace {Global.Namespace}
{{

    /// <summary>
    /// When applied to a partial static class the class will become a handle for a group of endpoints.
    /// Groups allow users to map several endpoints to a parent route such as /api/receips
    /// Groups will allow users to addapt common configuration such as auth and filters.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(""{Global.Namespace}"", ""{Global.Version}"")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false)]
    public sealed class {TypeName} : global::System.Attribute
    {{
        /// <summary>
        /// The route prefix for the group of endpoints
        /// </summary>
        public string RoutePrefix {{ get; private set; }}

        /// <summary>
        /// The group of endpoints tag name used for Open API
        /// </summary>
        public string? Tag {{ get; private set; }}

        /// <summary>
        /// The route group's parent group.
        /// A group with a provided parent prefix will map all the endpoints under the parent provided.
        /// </summary>
        public string ParentGroup {{ get; private set; }}

        /// <summary>
        /// When applied to a partial static class the class will become a handle for a group of endpoints.
        /// Groups allow users to map several endpoints to a parent route such as /api/receips
        /// Groups will allow users to addapt common configuration such as auth and filters.
        /// </summary>
        /// <param name=""routePrefix"">The route prefix for the group of endpoints</param>
        /// <param name=""parent"">The route group's parent group.</param>
        /// <param name=""tag"">The group of endpoints tag name used for Open API</param>
        public {TypeName}(string routePrefix, string? parent = null, string? tag = null)
        {{
            RoutePrefix = routePrefix;
            ParentGroup = parent;
            Tag = tag;
        }}
    }}
}}
";
}
