using Microsoft.CodeAnalysis;
using Scribbly.Stencil.Endpoints.Context;

namespace Scribbly.Stencil.Endpoints;

public static class EndpointHandlerExecution
{
    /// <summary>
    /// Writes the captured information about the handle method as a Minimal API endpoint.
    /// </summary>
    /// <param name="context">Generator Context</param>
    /// <param name="subject">Captured Method Context</param>
    public static void Generate(SourceProductionContext context, TargetMethodCaptureContext subject)
    {
        if (subject.IsConfigurable)
        {
            GenerateConfiguredEndpoint(context, subject);
            return;
        }
        
        GenerateSimpleEndpoint(context, subject);
    }

    private static void GenerateConfiguredEndpoint(SourceProductionContext context, TargetMethodCaptureContext subject)
    {
        var @namespace = subject.Namespace is not null 
            ? $"namespace {subject.Namespace};"
            : string.Empty;

        var span = new Span<char>(subject.MethodName!.ToCharArray());

        span[0] = char.ToLowerInvariant(span[0]);

        var builderParameter = new string(span.ToArray());
        
        var handlerCode = $@"
// <auto-generated/> @{DateTime.UtcNow}
#nullable enable

using Scribbly.Stencil;

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;

// -------------> PARENT:{subject.MemberOf} GROUP: {subject.GroupMode} CONFIG: {subject.ConfigurationMode}

{@namespace}

public partial class {subject.TypeName}: global::{subject.Namespace}.{subject.TypeName}.I{subject.MethodName}Configure
{{
    public interface I{subject.MethodName}Configure: global::Scribbly.Stencil.{ConfigureMarkerInterface.TypeName}
    {{
        void Configure{subject.MethodName}(global::Microsoft.AspNetCore.Builder.IEndpointConventionBuilder {builderParameter}Builder);
    }}

    /// <summary>
    /// Maps the method {subject.MethodName} to an Endpoint group with the Route {subject.HttpMethod?.ToUpper()} {subject.HttpRoute}.
    /// </summary>
    public global::Microsoft.AspNetCore.Builder.IEndpointConventionBuilder Map{subject.TypeName}{subject.MethodName}(global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder builder)
    {{
        var endpoint = builder.Map{subject.HttpMethod}(""{subject.HttpRoute}"", {subject.MethodName});

        Configure{subject.MethodName}(endpoint);
        
{subject.AddApiDocumentation()}
        
        return endpoint;
    }}
}}
";
        var handlerName = subject.Namespace is null ? $"{subject.TypeName}.{subject.MethodName}" : $"{subject.Namespace}.{subject.TypeName}.{subject.MethodName}";
        context.AddSource($"Handler.{handlerName}.g.cs", handlerCode);
    }

    private static void GenerateSimpleEndpoint(SourceProductionContext context, TargetMethodCaptureContext subject)
    {
        var @namespace = subject.Namespace is not null 
            ? $"namespace {subject.Namespace};"
            : string.Empty;
        
        var handlerCode = $@"
// <auto-generated/> @{DateTime.UtcNow}
#nullable enable

using Scribbly.Stencil;

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;

// -------------> {subject.MemberOf}

{@namespace}

public partial class {subject.TypeName}
{{
    /// <summary>
    /// Maps the method {subject.MethodName} to an Endpoint group with the Route {subject.HttpMethod?.ToUpper()} {subject.HttpRoute}.
    /// </summary>
    public global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder Map{subject.TypeName}{subject.MethodName}(global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder builder)
    {{
        var endpoint = builder.Map{subject.HttpMethod}(""{subject.HttpRoute}"", {subject.MethodName});

{subject.AddApiDocumentation()}
        
        return builder;
    }}
}}
";
        var handlerName = subject.Namespace is null ? $"{subject.TypeName}.{subject.MethodName}" : $"{subject.Namespace}.{subject.TypeName}.{subject.MethodName}";
        context.AddSource($"Handler.{handlerName}.g.cs", handlerCode);
    }

    private static string AddApiDocumentation(this TargetMethodCaptureContext subject)
    {
        return subject switch
        {
            { Name: not null, Description: null } => $"""
                                                              endpoint.WithName("{subject.Name}");
                                                      """,
            { Name: null, Description: not null } => $"""
                                                              endpoint.WithDescription("{subject.Description}");
                                                      """,
            { Name: not null, Description: not null } =>
                $"""
                         endpoint
                             .WithName("{subject.Name}")
                             .WithDescription("{subject.Description}");
                 """,
            _ => string.Empty
        };
    }
}