namespace Scribbly.Stencil.Attributes.Endpoints;

    internal static class EndpointBuilderAttribute
    {
        public const string FileName = "EndpointBuilderAttribute.g.cs";
        public const string TypeName = "EndpointBuilderAttribute";
        public const string UsageName = "EndpointBuilder";
        public const string TypeFullName = "Scribbly.Stencil.EndpointBuilder";
        public const string Value =
@$"
// <auto-generated/>
#nullable enable
namespace {Global.Namespace}
{{

    /// <summary>
    /// When applied to a partial static method the with an Endpoint Attribute the code generator will create a builder handler.
    /// This enables the consumer to intercept the build pipeline and add features to the endpoint.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(""{Global.Namespace}"", ""{Global.Version}"")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false)]
    public sealed class {TypeName} : global::System.Attribute
    {{
    }}
}}
";
    }
