namespace Scribbly.Stencil.Attributes.Endpoints;

    internal static class EndpointAttribute
    {
        public const string FileName = "EndpointAttribute.g.cs";
        public const string TypeName = "EndpointAttribute";
        public const string UsageName = "Endpoint";
        public const string TypeFullName = "Scribbly.Stencil.EndpointAttribute";
        public const string Value =
@$"
// <auto-generated/>
#nullable enable
namespace {Global.Namespace}
{{

    /// <summary>
    /// When applied to a partial static method the delegate will become a handler for an HTTP Request endpoint.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(""{Global.Namespace}"", ""{Global.Version}"")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false)]
    public abstract class {TypeName} : global::System.Attribute
    {{
        /// <summary>
        /// The route HTTP method
        /// </summary>
        public string Method {{ get; private set; }}
       
        /// <summary>
        /// The route for the endpoint
        /// </summary>
        public string Route {{ get; private set; }}

        /// <summary>
        /// A name for the HTTP endpoint used for API documentation and routing.
        /// </summary>
        public string? Name {{ get; private set; }}

        /// <summary>
        /// A description for the HTTP endpoint used for API documentation.
        /// </summary>
        public string? Description {{ get; private set; }}

        /// <summary>
        /// When applied to a partial static method the delegate will become a handler for an HTTP endpoint.
        /// </summary>
        public {TypeName}(string method, string route, string? name = null, string? description = null)
        {{
            Method = method;
            Route = route;
            Name = name;
            Description = description;
        }}
    }}
}}
";
    }
