namespace Scribbly.Stencil.Attributes.Endpoints;

    internal static class GetEndpointAttribute
    {
        public const string FileName = "GetEndpointAttribute.g.cs";
        public const string TypeName = "GetEndpointAttribute";
        public const string UsageName = "GetEndpoint";
        public const string TypeFullName = "Scribbly.Stencil.GetEndpoint";
        public const string Value =
@$"
// <auto-generated/>
#nullable enable
namespace {Global.Namespace}
{{

    /// <summary>
    /// When applied to a partial static method the delegate will become a handler for an HTTP GET endpoint.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(""{Global.Namespace}"", ""{Global.Version}"")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false)]
    public sealed class {TypeName} : global::{EndpointAttribute.TypeFullName}
    {{
        /// <summary>
        /// When applied to a partial static method the delegate will become a handler for an HTTP GET endpoint.
        /// </summary>
        public {TypeName}(string route, string? name = null, string? description = null) 
            :base(""Get"", route, name, description)
        {{
        }}
    }}
}}
";
    }
