namespace Scribbly.Stencil.Attributes.Endpoints;

    internal static class PutEndpointAttribute
    {
        public const string FileName = "PutEndpointAttribute.g.cs";
        public const string TypeName = "PutEndpointAttribute";
        public const string UsageName = "PutEndpoint";
        public const string TypeFullName = "Scribbly.Stencil.PutEndpoint";
        public const string Value =
@$"
// <auto-generated/>
#nullable enable
namespace {Global.Namespace}
{{

    /// <summary>
    /// When applied to a partial static method the delegate will become a handler for an HTTP PUT endpoint.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(""{Global.Namespace}"", ""{Global.Version}"")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false)]
    public sealed class {TypeName} : global::System.Attribute
    {{
        /// <summary>
        /// The route for the endpoint
        /// </summary>
        public string Route {{ get; private set; }}

        /// <summary>
        /// An endpoint name for the HTTP endpoint.
        /// </summary>
        public string? Name {{ get; private set; }}

        /// <summary>
        /// When applied to a partial static method the delegate will become a handler for an HTTP PUT endpoint.
        /// </summary>
        public {TypeName}(string route, string? name = null)
        {{
            Route = route;
            Name = name;
        }}
    }}
}}
";
    }
