namespace Scribbly.Stencil.Endpoints;

internal static class ConfigureMarkerInterface
{
    public const string FileName = "IEndpointConfigure.g.cs";
    public const string TypeName = "IEndpointConfigure";
    public const string TypeFullName = "Scribbly.Stencil.IEndpointConfigure";
    
    public static readonly string Value = 
        $$"""
          // <auto-generated/>
          #nullable enable

          namespace Scribbly.Stencil;

          /// <summary>
          /// Marks a type os a configurable endpoint group.
          /// This interface is automatically appended to the endpoint group class when the configure attribute is applied and used to enforce type safety.
          /// </summary>
          public interface {{TypeName}};
          """;
}
