namespace Scribbly.Stencil.Groups;

internal static class ConfigureMarkerInterface
{
    public const string FileName = "IGroupConfigure.g.cs";
    public const string TypeName = "IGroupConfigure";
    public const string TypeFullName = "Scribbly.Stencil.IGroupConfigure";
    
    public static readonly string Value = 
        $$"""
        // <auto-generated/>
        #nullable enable
        
        namespace Scribbly.Stencil;
        
        /// <summary>
        /// Marks a type os a configurable endpoint group.
        /// This interface is automatically appended to the endpoint group class when the configure attribute is applied and used to enforce type safety.
        /// <see cref="GroupMember{TGroup}"/>
        /// </summary>
        public interface {{TypeName}};
        """;
}
