namespace Scribbly.Stencil.Groups;

internal static class GroupMarkerInterface
{
    public const string FileName = "IGroup.g.cs";
    public const string TypeName = "IGroup";
    public const string TypeFullName = "Scribbly.Stencil.IGroup";
    
    public static readonly string Value = 
        """
        // <auto-generated/>
        #nullable enable
        
        namespace Scribbly.Stencil;
        
        /// <summary>
        /// Marks a type os an endpoint group.
        /// This interface is automatically appended to the endpoint group class and used to enforce type safety.
        /// <see cref="GroupMember{TGroup}"/>
        /// </summary>
        public interface IGroup;
        """;
}
