namespace Scribbly.Stencil.Endpoints;

    internal static class EndpointOutput
    {
        public const string FileName = "EndpointOutput.g.cs";
        public const string TypeName = "EndpointOutput";
        public const string UsageName = "Endpoint";
        public const string TypeFullName = "Scribbly.Stencil.EndpointOutput";
        public const string Value =
@$"
// <auto-generated/>
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;

namespace {Global.Namespace}
{{

    /// <summary>
    /// When applied to a partial static method the delegate will become a handler for an HTTP Request endpoint.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(""{Global.Namespace}"", ""{Global.Version}"")]
    public static class {TypeName}Extensions
    {{
       
        public static void Map{TypeName}(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder builder)
        {{
            builder.MapGet(""/test"", () => Results.Ok());
        }}
    }}
}}
";
    }
